In [55]:
import pandas as pd
import numpy as np
import rebound
import tools

a = np.zeros(1);e = np.zeros(1);inc = np.zeros(1);phi = np.zeros(1)
t = np.zeros(1);

r2d = 180/np.pi
objname = 'Ceres'
sbody = 'Ceres'
filename = "Asteroids/"+objname
#filename = "TNOs/"+objname
sa = rebound.SimulationArchive(filename+'/archive.bin')
print(sa.tmin)
print(sa.tmax)

planets = ['mercury','venus','earth','mars','jupiter','saturn','uranus','neptune']

a = np.zeros(len(sa));
e = np.zeros(len(sa));
inc = np.zeros(len(sa));
qp = np.zeros(len(sa),dtype=complex);
ptp = np.zeros(len(sa));
qtp = np.zeros(len(sa));
kh = np.zeros(len(sa),dtype=complex);
#k = np.zeros(len(sa));
t = np.zeros(len(sa));
npl = 9

qppl = np.asfortranarray(np.zeros(shape=[len(sa),npl],dtype=complex));
#qpl = np.asfortranarray(np.zeros(shape=[len(sa),npl]));
khpl = np.asfortranarray(np.zeros(shape=[len(sa),npl],dtype=complex));
#kpl = np.asfortranarray(np.zeros(shape=[len(sa),npl]));

hpl = np.zeros((len(sa),npl))
kpl = np.zeros((len(sa),npl))
ppl = np.zeros((len(sa),npl))
qpl = np.zeros((len(sa),npl))

hpart = np.zeros(len(sa))
kpart = np.zeros(len(sa))
ppart = np.zeros(len(sa))
qpart = np.zeros(len(sa))

apl = np.zeros((len(sa),npl))
for j,sim in enumerate(sa):
    tp = sim.particles[sbody+"_bf"]
    com = sim.calculate_com()
    o = tp.calculate_orbit(com)
    t[j] = sim.t
    a[j] = o.a
    p = np.sin(o.inc)*np.sin(o.Omega)
    q = np.sin(o.inc)*np.cos(o.Omega)
    ptp[j] = p
    qtp[j] = q
    qp[j] = 1j*p + q
    h = (o.e)*np.sin(o.Omega+o.omega)
    k = (o.e)*np.cos(o.Omega+o.omega)
    
    hpart[j] = h
    kpart[j] = k
    ppart[j] = p
    qpart[j] = q
    
    kh[j] = 1j*k + h
    
    e[j] = o.e
    inc[j] = o.inc*180/np.pi
    #print(sim.particles[1].inc)
    for i in range (0,npl):
        #print(planets[i])
        
        pl = sim.particles[i]
        o = pl.calculate_orbit(com)
        
        apl[j,i] = o.a
        ptemp = np.sin(o.inc)*np.sin(o.Omega)
        qtemp = np.sin(o.inc)*np.cos(o.Omega)
        qppl[j,i] = 1j*ptemp + qtemp
        htemp = (o.e)*np.sin(o.Omega+o.omega)
        ktemp = (o.e)*np.cos(o.Omega+o.omega)
        khpl[j,i] = 1j*ktemp + htemp
        hpl[j,i] = htemp
        kpl[j,i] = ktemp
        ppl[j,i] = ptemp
        qpl[j,i] = qtemp

0.0
20000000.0


In [56]:
series = pd.DataFrame(columns=['t','a','ecc','inc','p','q','h','k','hj','kj','pj','qj','hs','ks','ps','qs','hu','ku','pu','qu','hn','kn','pn','qn'])

print(len(hpl),len(hpl[0,:]))
series['t'] = t
series['a'] = a
series['e'] = e
series['inc'] = inc
series['p'] = ppart
series['q'] = qpart
series['h'] = hpart
series['k'] = kpart
series['hmc'] = hpl[:,0]
series['kmc'] = kpl[:,0]
series['pmc'] = ppl[:,0]
series['qmc'] = qpl[:,0]
series['hv'] = hpl[:,1]
series['kv'] = kpl[:,1]
series['pv'] = ppl[:,1]
series['qv'] = qpl[:,1]
series['he'] = hpl[:,2]
series['ke'] = kpl[:,2]
series['pe'] = ppl[:,2]
series['qe'] = qpl[:,2]
series['hmr'] = hpl[:,3]
series['kmr'] = kpl[:,3]
series['pmr'] = ppl[:,3]
series['qmr'] = qpl[:,3]
series['hj'] = hpl[:,4]
series['kj'] = kpl[:,4]
series['pj'] = ppl[:,4]
series['qj'] = qpl[:,4]
series['hs'] = hpl[:,5]
series['ks'] = kpl[:,5]
series['ps'] = ppl[:,5]
series['qs'] = qpl[:,5]
series['hu'] = hpl[:,6]
series['ku'] = kpl[:,6]
series['pu'] = ppl[:,6]
series['qu'] = qpl[:,6]
series['hn'] = hpl[:,7]
series['kn'] = kpl[:,7]
series['pn'] = ppl[:,7]
series['qn'] = qpl[:,7]

series.to_csv(filename+'/series.csv')

200001 9


In [57]:
print(len(sim.particles))
print(apl[:,0])
print(apl[:,1])
print(apl[:,2])
print(apl[:,3])
print(apl[:,4])
print(apl[:,5])
print(apl[:,6])
print(apl[:,7])

9
[0.00417664 0.00369827 0.00355992 ... 0.00287113 0.00361433 0.00393199]
[0.7159571  0.73105785 0.73719002 ... 0.72144577 0.72609832 0.73346744]
[1.01626819 0.98305448 1.00566794 ... 1.00472689 0.99248581 1.00251304]
[1.51922225 1.5398925  1.5333361  ... 1.53256158 1.52815696 1.50239854]
[5.16958273 5.16957603 5.17394754 ... 5.17031937 5.17450886 5.16893986]
[9.52620583 9.519402   9.52406816 ... 9.53845783 9.53685799 9.52635421]
[19.18461624 19.18504202 19.18777973 ... 19.18320208 19.19305587
 19.18472991]
[30.06834593 30.06844679 30.06957538 ... 30.06818506 30.06632307
 30.06273859]


In [45]:
print(h-hpl[:,8])

IndexError: index 8 is out of bounds for axis 1 with size 8